//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.03.07 at 11:46:33 AM CET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://elite.polito.it/domotics/dog/rules/rule_definition", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED, xmlns={@XmlNs(prefix="dogrules", namespaceURI="http://elite.polito.it/domotics/dog/rules/rule_definition")})
package it.polito.elite.dog.addons.rules.schemalibrary;

import javax.xml.bind.annotation.*;